include_guard(GLOBAL)

get_filename_component(VOLKENGINE_REPOSITORY_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)

set(VOLKENGINE_BOOTSTRAP_DIR "${VOLKENGINE_REPOSITORY_ROOT}/out/bootstrap" CACHE PATH "Repo-local directory for downloaded build tools and SDKs")
option(VOLKENGINE_BOOTSTRAP_TOOLS "Download repo-local build tools/SDKs when the host does not provide them" ON)
option(VOLKENGINE_BOOTSTRAP_NINJA "Download a repo-local Ninja binary when the selected Ninja generator cannot find one" ON)
option(VOLKENGINE_BOOTSTRAP_VULKAN_SDK "Download a repo-local LunarG Vulkan SDK when Vulkan headers/libs or glslc are missing" ON)

set(VOLKENGINE_NINJA_VERSION "1.12.1" CACHE STRING "Pinned Ninja version used by the repo-local bootstrap")
set(VOLKENGINE_VULKAN_SDK_LINUX_VERSION "1.4.350.1" CACHE STRING "Pinned LunarG Vulkan SDK version used on Linux")
set(VOLKENGINE_VULKAN_SDK_WINDOWS_VERSION "1.4.350.0" CACHE STRING "Pinned LunarG Vulkan SDK version used on Windows")

function(volkengine_path_separator out_var)
    if(CMAKE_HOST_WIN32)
        set(${out_var} ";" PARENT_SCOPE)
    else()
        set(${out_var} ":" PARENT_SCOPE)
    endif()
endfunction()

function(volkengine_write_bootstrap_environment)
    get_property(_paths GLOBAL PROPERTY VOLKENGINE_BOOTSTRAP_BIN_DIRS)
    if(NOT _paths)
        return()
    endif()

    file(MAKE_DIRECTORY "${VOLKENGINE_BOOTSTRAP_DIR}")

    string(REPLACE ";" ":" _sh_paths "${_paths}")
    file(WRITE "${VOLKENGINE_BOOTSTRAP_DIR}/env.sh"
        "# Generated by VolkEngine CMake bootstrap. Source this only if you want the repo-local tools in this shell.\n"
        "export PATH=\"${_sh_paths}:$PATH\"\n")

    set(_ps_paths "")
    foreach(_path IN LISTS _paths)
        if(_ps_paths STREQUAL "")
            set(_ps_paths "${_path}")
        else()
            string(APPEND _ps_paths ";${_path}")
        endif()
    endforeach()
    file(WRITE "${VOLKENGINE_BOOTSTRAP_DIR}/env.ps1"
        "# Generated by VolkEngine CMake bootstrap. Dot-source this only if you want the repo-local tools in this PowerShell.\n"
        "\$env:Path = \"${_ps_paths};\$env:Path\"\n")
endfunction()

function(volkengine_register_bootstrap_bin directory)
    if(NOT directory)
        return()
    endif()

    get_filename_component(_dir "${directory}" ABSOLUTE)
    if(NOT EXISTS "${_dir}")
        return()
    endif()

    get_property(_paths GLOBAL PROPERTY VOLKENGINE_BOOTSTRAP_BIN_DIRS)
    if(NOT _paths)
        set(_paths "")
    endif()
    list(PREPEND _paths "${_dir}")
    list(REMOVE_DUPLICATES _paths)
    set_property(GLOBAL PROPERTY VOLKENGINE_BOOTSTRAP_BIN_DIRS "${_paths}")

    volkengine_path_separator(_sep)
    if(DEFINED ENV{PATH} AND NOT "$ENV{PATH}" STREQUAL "")
        set(ENV{PATH} "${_dir}${_sep}$ENV{PATH}")
    else()
        set(ENV{PATH} "${_dir}")
    endif()

    volkengine_write_bootstrap_environment()
endfunction()

function(volkengine_register_bootstrap_bin_if_repo_local directory)
    if(NOT directory)
        return()
    endif()

    get_filename_component(_dir "${directory}" ABSOLUTE)
    get_filename_component(_bootstrap_dir "${VOLKENGINE_BOOTSTRAP_DIR}" ABSOLUTE)
    string(FIND "${_dir}" "${_bootstrap_dir}" _bootstrap_prefix)
    if(_bootstrap_prefix EQUAL 0)
        volkengine_register_bootstrap_bin("${_dir}")
    endif()
endfunction()

function(volkengine_download_file name url sha256 output)
    if(EXISTS "${output}")
        file(SHA256 "${output}" _actual_sha256)
        if(_actual_sha256 STREQUAL "${sha256}")
            return()
        endif()
        message(STATUS "${name}: cached file hash mismatch; downloading a fresh copy")
        file(REMOVE "${output}")
    endif()

    get_filename_component(_output_dir "${output}" DIRECTORY)
    file(MAKE_DIRECTORY "${_output_dir}")
    set(_temporary_output "${output}.tmp")
    file(REMOVE "${_temporary_output}")

    message(STATUS "${name}: downloading ${url}")
    file(DOWNLOAD
        "${url}"
        "${_temporary_output}"
        EXPECTED_HASH "SHA256=${sha256}"
        TLS_VERIFY ON
        STATUS _download_status
        LOG _download_log
        SHOW_PROGRESS)
    list(GET _download_status 0 _download_code)
    list(GET _download_status 1 _download_message)
    if(NOT _download_code EQUAL 0)
        file(REMOVE "${_temporary_output}")
        message(FATAL_ERROR "${name}: download failed: ${_download_message}\n${_download_log}")
    endif()

    file(RENAME "${_temporary_output}" "${output}")
endfunction()

function(volkengine_extract_archive name archive destination marker)
    if(EXISTS "${marker}")
        return()
    endif()

    get_filename_component(_destination_parent "${destination}" DIRECTORY)
    file(MAKE_DIRECTORY "${_destination_parent}")
    set(_temporary_destination "${destination}.tmp")
    file(REMOVE_RECURSE "${_temporary_destination}")
    file(MAKE_DIRECTORY "${_temporary_destination}")

    message(STATUS "${name}: extracting ${archive}")
    file(ARCHIVE_EXTRACT INPUT "${archive}" DESTINATION "${_temporary_destination}")
    file(REMOVE_RECURSE "${destination}")
    file(RENAME "${_temporary_destination}" "${destination}")
    file(WRITE "${marker}" "${name}\n${archive}\n")
endfunction()

function(volkengine_bootstrap_ninja)
    if(NOT VOLKENGINE_BOOTSTRAP_TOOLS OR NOT VOLKENGINE_BOOTSTRAP_NINJA)
        return()
    endif()
    if(NOT CMAKE_GENERATOR MATCHES "Ninja")
        return()
    endif()

    if(DEFINED CMAKE_MAKE_PROGRAM AND EXISTS "${CMAKE_MAKE_PROGRAM}")
        get_filename_component(_ninja_bin_dir "${CMAKE_MAKE_PROGRAM}" DIRECTORY)
        volkengine_register_bootstrap_bin_if_repo_local("${_ninja_bin_dir}")
        message(STATUS "Using configured Ninja: ${CMAKE_MAKE_PROGRAM}")
        return()
    endif()

    find_program(_system_ninja NAMES ninja ninja-build NO_CACHE)
    if(_system_ninja)
        set(CMAKE_MAKE_PROGRAM "${_system_ninja}" CACHE FILEPATH "Ninja executable" FORCE)
        message(STATUS "Using system Ninja: ${_system_ninja}")
        return()
    endif()

    if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
        set(_ninja_archive_name "ninja-linux.zip")
        set(_ninja_url "https://github.com/ninja-build/ninja/releases/download/v${VOLKENGINE_NINJA_VERSION}/${_ninja_archive_name}")
        set(_ninja_sha256 "6f98805688d19672bd699fbbfa2c2cf0fc054ac3df1f0e6a47664d963d530255")
        set(_ninja_executable "${VOLKENGINE_BOOTSTRAP_DIR}/ninja/ninja")
    elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
        set(_ninja_archive_name "ninja-win.zip")
        set(_ninja_url "https://github.com/ninja-build/ninja/releases/download/v${VOLKENGINE_NINJA_VERSION}/${_ninja_archive_name}")
        set(_ninja_sha256 "f550fec705b6d6ff58f2db3c374c2277a37691678d6aba463adcbb129108467a")
        set(_ninja_executable "${VOLKENGINE_BOOTSTRAP_DIR}/ninja/ninja.exe")
    else()
        message(FATAL_ERROR "Ninja bootstrap is supported on Linux and Windows hosts only. Install Ninja or use a different CMake generator on ${CMAKE_HOST_SYSTEM_NAME}.")
    endif()

    set(_ninja_archive "${VOLKENGINE_BOOTSTRAP_DIR}/downloads/${_ninja_archive_name}")
    set(_ninja_marker "${VOLKENGINE_BOOTSTRAP_DIR}/ninja/.${VOLKENGINE_NINJA_VERSION}.complete")
    volkengine_download_file("Ninja ${VOLKENGINE_NINJA_VERSION}" "${_ninja_url}" "${_ninja_sha256}" "${_ninja_archive}")
    volkengine_extract_archive("Ninja ${VOLKENGINE_NINJA_VERSION}" "${_ninja_archive}" "${VOLKENGINE_BOOTSTRAP_DIR}/ninja" "${_ninja_marker}")

    if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
        file(CHMOD "${_ninja_executable}"
            PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
    endif()
    if(NOT EXISTS "${_ninja_executable}")
        message(FATAL_ERROR "Ninja bootstrap completed but ${_ninja_executable} was not produced")
    endif()

    set(CMAKE_MAKE_PROGRAM "${_ninja_executable}" CACHE FILEPATH "Repo-local Ninja executable" FORCE)
    volkengine_register_bootstrap_bin("${VOLKENGINE_BOOTSTRAP_DIR}/ninja")
    message(STATUS "Using bootstrapped Ninja: ${_ninja_executable}")
endfunction()

volkengine_bootstrap_ninja()
